resources:
  - name: jpipe_gitrepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: skylark05/jpipe
      files:
        exclude: .*\.yml
      buildOn:
        commit: true

pipelines:
  - name: TestFilters
    steps:
      - name: dummy
        type: Bash
        configuration:
          inputResources:
            - name: jpipe_gitrepo
        execution:
          onExecute:
            - echo "Hello World!"

# Dummy edit
