resources:
  - name: artifactory_go_example
    type: GitRepo
    configuration:
      path: skylark05/artifactory-go-example
      gitProvider: github
  - name: go_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: go_example_build
      buildNumber: 1
  - name: files
    type: FileSpec
    configuration:
      pattern: ragesh-generic/*.txt
 
pipelines:
  - name: go_example_build
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: go
          outputLocation: /tmp/dist
          outputFile: hello
          inputResources:
            - name: artifactory_go_example
          #integrations:
          #  - name: art
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
      #- name: push_go_binary
      #  type: PushArtifactoryPackage
      #  configuration:
      #    targetRepo: ragesh-generic
      #    integrations:
      #      - name: art
      #    inputSteps:
      #      - name: build_go
      #- name: publish_go_build
      #  type: PublishBuildInfo
      #  configuration:
      #    integrations:
      #      - name: art
      #    inputSteps:
      #      - name: push_go_binary
      #    outputResources:
      #      - name: go_build_info
