resources:
  - name: dockerbuild_commit_gitrepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: skylark05/dockerbuild
      buildOn:
        commit: true
        
  - name: dockerbuild_pr_gitrepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: skylark05/dockerbuild
      buildOn:
        pullRequestCreate: true

  - name: myDockerImage
    type: Image
    configuration:
      registry: dockerHub
      imageName: ragesh/busybox
      imageTag: latest
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: ragesh-app
      buildNumber: 1

pipelines:
  - name: gitrepo_pr_pipe
    steps:
      - name: on_pr
        type: Bash
        configuration:
          inputResources:
            - name: dockerbuild_pr_gitrepo
        execution:
          onExecute:
            - echo "Hello, World!"
            
  - name: gitrepo_commit_pipe
    steps:
      - name: on_commit
        type: Bash
        configuration:
          inputResources:
            - name: dockerbuild_commit_gitrepo
        execution:
          onExecute:
            - echo "Hello, World!"
          
  - name: JenkinsPipe
    steps:
      - name: app_ci
        type: Jenkins
        configuration:
          integrations:
            - name: jenkins
          outputResources:
            - name: myDockerImage
            - name: myBuildInfo
